[tools]
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
selene = "kampfkarren/selene@0.31.0"
lune = "filiptibell/lune@0.10.4"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
luau-lsp = "johnnymorganz/luau-lsp@1.68.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
darklua = "seaofvoices/darklua@0.19.0"
StyLua = "JohnnyMorganz/StyLua@2.5.2"
