name: lint

on:
  [push]

jobs:
  generate_readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bash
        run: sudo apt-get install -y bash

      - name: Set execute permission for script
        run: chmod +x scripts/generateReadMe.sh

      - name: Run generateReadMe.sh
        run: scripts/generateReadMe.sh

  lint:
    name: "Selene lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Run Selene
        run: selene lib

  build_docs:
    name: Build docs
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i -g moonwave@latest
      - name: Build
        run: |
          moonwave build
