name: lint

on:
  [push]

jobs:
  lint:
    name: "Selene lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Run Selene
        run: selene lib
